#!/bin/bash

# printf parameters information
print_info()
{
echo "Usage: sudo ./DSI-720x1280-show"
echo "Usage: sudo ./DSI-720x1280-show i2c0"
echo "Usage: sudo ./DSI-720x1280-show i2c1"
echo "Usage: sudo ./DSI-720x1280-show i2c1 dsi0"
echo "Usage: sudo ./DSI-720x1280-show i2c0 dsi0"
echo "Usage: sudo ./DSI-720x1280-show -h or --help"
echo "Usage: sudo ./DSI-720x1280-show clean"
echo "Usage: sudo ./DSI-720x1280-show uninstall"
echo "i2c0--Using I2C0 bus"
echo "i2c1--Using I2C1 bus"
echo "dsi0--Using DSI0 interface"
echo "DSI uses 2lanes DSI1 interface by default"
echo "If there are no parameters, I2C0 bus and 2 lanes DSI1 interface will be used by default"
echo "-h or --Help to show this help information"
echo "clean--Clean up the compile driver"
echo "uninstall--Uninstall the currently installed driver"
}

clean_config()
{
sudo sed -i '/^[^#].*vc4-kms-dsi/s/^/#/' /boot/firmware/config.txt
sudo sed -i "/vc4-kms-dsi-qdtft-panel/d" /boot/firmware/config.txt
}

uninstall_driver()
{
sudo sed -i "/vc4-kms-dsi-qdtft-panel/d" /boot/firmware/config.txt
if [ -f /lib/modules/$(uname -r)/updates/panel-qdtft-dsi.ko.xz ]; then
sudo rm -rf /lib/modules/$(uname -r)/updates/panel-qdtft-dsi.ko.xz
fi
if [ -f /lib/modules/$(uname -r)/updates/panel-qdtft-regulator.ko.xz ]; then
sudo rm -rf /lib/modules/$(uname -r)/updates/panel-qdtft-regulator.ko.xz
fi
if [ -f /boot/firmware/overlays/vc4-kms-dsi-qdtft-panel.dtbo ]; then
sudo rm -rf /boot/firmware/overlays/vc4-kms-dsi-qdtft-panel.dtbo
fi
if [ -f /home/$username/.current_installed ]; then
sudo rm -rf /home/$username/.current_installed
fi
}

username=`logname | tr -d '\n'`
deb_version=`cat /etc/debian_version | tr -d '\n'`
ko_result=0

#configue config.txt
if [ $# -eq 0 ]; then
clean_config
sudo echo "dtoverlay=vc4-kms-dsi-qdtft-panel" >> /boot/firmware/config.txt
elif [ $# -eq 1 ]; then
if [ "$1" == "i2c0" ] || [ "$1" == "i2c1" ]; then
clean_config
sudo echo "dtoverlay=vc4-kms-dsi-qdtft-panel,$1" >> /boot/firmware/config.txt
elif [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
echo "sudo ./DSI-720x1280-show -h or sudo ./DSI-720x1280-show --help"
echo "will show this help information:"
print_info
exit
elif [ "$1" == "clean" ]; then
if [[ "$deb_version" < "13.5" ]]; then
cd ./DSI-720x1280_6.12
else
cd ./DSI-720x1280_6.18
fi
sudo make clean
exit
elif [ "$1" == "uninstall" ]; then
uninstall_driver
exit
else
echo -e "\033[31mThe first argument is invalid.\033[0m"
print_info
exit
fi
elif [ $# -eq 2 ]; then
if [ "$1" == "i2c0" ] || [ "$1" == "i2c1" ]; then
if [ "$2" == "dsi0" ]; then
clean_config
sudo echo "dtoverlay=vc4-kms-dsi-qdtft-panel,$1,$2" >> /boot/firmware/config.txt
else
echo -e "\033[31mThe second argument is invalid.\033[0m"
print_info
exit
fi
else
echo -e "\033[31mThe first argument is invalid.\033[0m"
print_info
exit
fi
else
print_info
echo -e "\033[31mToo many parameters, Up to two parameters are allowed.\033[0m"
exit
fi

if ls /lib/modules/$(uname -r)/updates/*ko.xz > /dev/null 2>&1; then
ko_result=1
else
ko_result=0
fi

#compile driver
if [[ "$deb_version" < "13.5" ]]; then
cd ./DSI-720x1280_6.12
else
cd ./DSI-720x1280_6.18
fi
sudo make clean
sudo make
if [ $? -ne 0 ]; then
echo -e "\033[31mComple driver error!.\033[0m"
if [ $ko_result -eq 0 ]; then
clean_config
fi
exit
fi
sudo make install
sudo cp -rf $PWD/../overlays/vc4-kms-dsi-qdtft-panel.dtbo /boot/firmware/overlays
sudo touch /home/$username/.current_installed
sudo echo "720x1280" > /home/$username/.current_installed 
sudo reboot
